CREATE TABLE url(
    id INT AUTO_INCREMENT PRIMARY KEY,
    originalUrl VARCHAR(255) NOT NULL,
    shortUrl VARCHAR(255) NOT NULL,
    countClick INT DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);