CREATE TABLE url(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) DEFAULT NOT NULL,
    originalUrl VARCHAR(255) NOT NULL,
    shortCode VARCHAR(255) NOT NULL,
    shortUrl VARCHAR(255) NOT NULL,
    countClick INT DEFAULT 0,
    active BOOLEAN DEFAULT FALSE,
    user_id VARCHAR(32),
    anonymous_id VARCHAR(255),
    expirationDate TIMESTAMP NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user (
    id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
    password_hash TEXT,
    image VARCHAR(255),
    isAdmin BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY id_unique (id)
);
